name: Run Jupyter Notebook Daily

on:
  schedule:
    - cron: "30 13 * * *"  # Runs at 1:30 PM UTC
  workflow_dispatch:       # Allows manual execution

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install jupyter nbconvert pandas numpy openai tensorflow scikit-learn transformers

      - name: Set OpenAI API Key
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Run Jupyter Notebook with Debugging
        run: |
          echo "🚀 Running Jupyter Notebook..."
          ls -lh windborne.ipynb  # Check if the notebook exists
          jupyter nbconvert --to notebook --execute windborne.ipynb --output docs/output.ipynb --debug
          echo "✅ Notebook execution completed."

      - name: Debug - Check If Output Exists
        run: |
          echo "🔍 Checking output files..."
          ls -lh docs/

      - name: Commit and Push Output
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs/index.html docs/output.ipynb docs/output.json
          git commit -m "Auto-run notebook - $(date)" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
