name: Run Jupyter Notebook Daily

on:
  schedule:
    - cron: "30 13 * * *"  # Runs at 1:30 PM UTC
  workflow_dispatch:       # Allows manual execution

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip  # Ensure latest pip version
          pip install jupyter nbconvert pandas numpy openai tensorflow scikit-learn transformers
          pip install langchain langchain_core langchain_openai langchain_community  # Added missing dependencies

      - name: Check Installed Python Packages
        run: |
          echo "✅ Checking installed packages..."
          pip list | grep langchain || true  # Debugging: Ensure langchain is installed

      - name: Set OpenAI API Key
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Ensure Output Directory Exists
        run: mkdir -p docs  # Prevents errors if docs/ is missing

      - name: Clear Notebook Output Before Running
        run: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --to notebook --inplace windborne.ipynb

      - name: Run Jupyter Notebook
        env:
          FORCE_EXECUTION: ${{ github.run_id }}
        run: |
          echo "🚀 Running Jupyter Notebook..."
          jupyter nbconvert --to notebook --execute windborne.ipynb --output docs/output.ipynb --debug || exit 1
          echo "✅ Notebook execution completed."
          
      - name: Debug - Check If Output Exists
        run: |
          echo "🔍 Checking output files..."
          ls -lh docs/

      - name: Commit and Push Output
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Auto-run notebook - $(date)" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
